# This is the default configuration for a resetti profile.
# You can delete or ignore any sections which are not applicable.

[general]
# The type of reset style to use.
# Available options:
# - standard    Traditional single/multi-instance resetting for random seeds.
# - wall        Wall-style resetting for random seeds.
type = "standard"

# Whether or not to count the amount of resets performed.
count_resets = false

# The file to use for counting resets. This can be left blank
# if count_resets is disabled.
resets_file = ""

# Here, you can set various commands or shell scripts to run when certain
# events occur. Anything left blank will be ignored.
[hooks]
# The command/script to run when a reset from the wall occurs.
wall_reset = ""

# The command/script to run when a reset occurs.
reset = ""

# The command/script to run when an instance is locked on the wall.
lock = ""

# The command/script to run when an instance is unlocked on the wall.
unlock = ""

[obs]
# Whether or not to enable OBS websocket support. This is *required* for wall.
enabled = false

# The port to connect to OBS websocket on.
port = 4440

# The password to use when connecting. This can be left blank if you have
# authentication disabled in OBS websocket.
password = ""

[reset]
# The amount of milliseconds to wait before certain actions (e.g. stretching
# instance windows and clicking the mouse with `click_on_focus`.)
delay = 50

# Whether or not to automatically unpause the game when an instance is focused.
unpause_on_focus = true

# Whether or not to automatically click the mouse when focusing an instance.
# When disabled, you will have to click the mouse yourself. This is toggleable
# as the old behavior was to not click at all.
click_on_focus = true

# - You can ignore any keybindings here which do not apply to your reset style.
# - Alphanumerical and Fn keys (1-12) are supported.
# - If you'd like to use another key, use the syntax "code100" where 100 is the
#   keycode of the given key.
# - You can supply modifiers (Shift, Control, Alt) as well.
# - The values written are not case sensitive (e.g. `a` and `A` are equivalent,
#   specify the `Shift` modifier.)
# - There is no distinction between the left and right modifier keys.
# - For the wall keys, you may only specify modifiers. For example, if you specify
#   Shift as your wall instance reset keybind, pressing Shift-1 will reset the
#   first instance (if you have mouse support enabled, shift clicking will work
#   as well.) You can leave the keybind blank for no modifier.
# - Do not have multiple identical keybinds.
#
#   Examples:
#               `A` => The A key.
#               `a` => The A key.
#         `Shift-A` => The A key, only when Shift is held.
#  `Ctrl-Shift-F12` => The F12 key with Control and Shift held.
#         `code135` => The Menu key on my keyboard layout. Use xmodmap to find your desired key.
#
[keybinds]
# Pressing this will focus the current instance.
# If you on the wall, pressing this will send you back to the OBS projector.
focus = "Ctrl-Shift-F"

# Pressing this will reset the current instance.
# If you are on the wall, pressing this will reset all instances.
reset = "Ctrl-Shift-R"

# Pressing this will reset the selected instance.
wall_reset = ""

# Pressing this will play the selected instance and reset all other instances.
wall_reset_others = "Ctrl-Shift"

# Pressing this will play the selected instance.
wall_play = "Shift"

# Pressing this will lock the selected instance.
wall_lock = "Ctrl"

[wall]
# Whether or not to press F1 when focusing instances. If you use this, turn on
# f1 in your standard settings file.
hide_gui = false

# Whether or not to stretch windows while on the wall for better visibility.
# Works with or without fullscreen.
stretch_windows = false

# The width to stretch windows to on the wall scene.
stretch_width = 1600

# The height to stretch windows to on the wall scene.
stretch_height = 300

# The width to unstretch windows to when being played.
unstretch_width = 1920

# The height to unstretch windows to when being played.
unstretch_height = 1080

# Whether or not to enable mouse support on the wall. Enabling this will allow
# you to click on instances to perform various actions instead of having to use
# the number keys. Note that enabling this does not disable the number keys.
use_mouse = false

# If enabled, resetting from within an instance will switch to the first locked
# instance (if any) instead of going back to the wall.
goto_locked = false

# Whether or not to create the "sleepbg.lock" file when an instance is being
# played. Requires SleepBackground >=3.6 to have any effect. 
sleepbg_lock = true

# You can supply a custom path to "sleepbg.lock" here in case you set the
# Java USER.HOME property to somewhere else. Leave blank to use the default,
# which is your home directory.
sleepbg_lock_path = "/home/my_user"

# More advanced wall settings, mainly aimed towards increasing performance.
[advanced_wall]
# Whether or not to use advanced affinity. All other affinity settings below
# only take effect if this is enabled. All affinity settings must be equal to
# or less than the number of CPU threads you have.
#
# Instance types:
# - Idle:   Done generating, paused
# - Low:    On the preview, generated more than low_threshold
# - Mid:    A high priority instance in the background while another instance is being played
# - High:   On the dirt screen or below low_threshold
# - Active: The instance currently being played
affinity = false

# Number of CPUs to run idle instances on.
affinity_idle = 1

# Number of CPUs to run low priority instances on.
affinity_low = 4

# Number of CPUs to run mid priority instances on.
affinity_mid = 8

# Number of CPUs to run high priority instances on.
affinity_high = 12

# Number of CPUs to run the actively played instance on.
affinity_active = 12

# The world generation percentage to reach before moving an instance
# from high priority to low priority.
low_threshold = 20
