# This is the default configuration for a resetti profile.
# You can delete or ignore any sections which are not applicable.

[general]
# The type of reset style to use.
# Available options:
# - standard    Traditional single/multi-instance resetting for random seeds.
# - wall        Wall-style resetting for random seeds.
type = "standard"

# Whether or not to count the amount of resets performed.
count_resets = false

# The file to use for counting resets. This can be left blank
# if count_resets is disabled.
resets_file = ""

# Here, you can set various commands or shell scripts to run when certain
# events occur. Anything left blank will be ignored.
[hooks]
# The command/script to run when a reset from the wall occurs.
wall_reset = ""

# The command/script to run when a reset occurs.
reset = ""

# The command/script to run when an instance is locked on the wall.
lock = ""

# The command/script to run when an instance is unlocked on the wall.
unlock = ""

# Moving wall is the modern wall arrangement where instances move between
# sections of the screen based on their state.

[moving_wall]
# Whether to use moving wall or not.
use_moving_wall = false

# Set a keybind to reset the first loaded instance in the loading view.
# The same rules for reset keybinds work here.
# Eg: reset_first_loaded = "R"
reset_first_loaded = "R"

# Set a keybind to lock the first loaded instance.
# The same rules for reset keybinds work here.
# Eg: lock_first_loaded = "L"
lock_first_loaded = "L"

# Set a keybind to unlock the first locked instance.
# The same rules for reset keybinds work here.
# Eg: unlock_first_loaded = "Ctrl-L"
unlock_first_loaded = "Ctrl-L"

# Set a keybind to play the first locked instance.
# The same rules for reset keybinds work here.
# Eg: play_first_locked = "Shift-L"
play_first_locked = "Shift-L"

# Set a keybind to play the first loaded instance.
# The same rules for reset keybinds work here.
# Eg: play_first_loaded = "Shift-R"
play_first_loaded = "Shift-R"

[obs]
# Whether or not to enable OBS websocket support. This is *required* for wall and moving_wall.
enabled = false

# The port to connect to OBS websocket on.
port = 4440

# The password to use when connecting. This can be left blank if you have
# authentication disabled in OBS websocket.
password = ""

[reset]
# The time in milliseconds to wait between switching windows and performing
# actions on those windows. Increase if certain features (e.g. unpausing,
# instance stretching) are inconsistent.
delay = 50

# The time in milliseconds to wait after entering preview/finishing world
# generation before pausing. Increase if pausing is inconsistent.
pause_delay = 50

# Whether or not to automatically unpause the game when an instance is focused.
unpause_on_focus = true

# - You can ignore any keybindings here which do not apply to your reset style.
# - Alphanumerical and Fn keys (1-12) are supported.
# - If you'd like to use another key, use the syntax "code100" where 100 is the
#   keycode of the given key.
# - You can supply modifiers (Shift, Control, Alt) as well.
# - The values written are not case sensitive (e.g. `a` and `A` are equivalent,
#   specify the `Shift` modifier.)
# - There is no distinction between the left and right modifier keys.
# - For the wall keys, you may only specify modifiers. For example, if you specify
#   Shift as your wall instance reset keybind, pressing Shift-1 will reset the
#   first instance (if you have mouse support enabled, shift clicking will work
#   as well.) You can leave the keybind blank for no modifier.
# - Do not have multiple identical keybinds.
#
#   Examples:
#               `A` => The A key.
#               `a` => The A key.
#         `Shift-A` => The A key, only when Shift is held.
#  `Ctrl-Shift-F12` => The F12 key with Control and Shift held.
#         `code135` => The Menu key on my keyboard layout. Use xmodmap to find your desired key.
#
[keybinds]
# Pressing this will focus the current instance.
# If you on the wall, pressing this will send you back to the OBS projector.
focus = "Ctrl-Shift-F"

# Pressing this will reset the current instance.
# If you are on the wall, pressing this will reset all instances.
reset = "Ctrl-Shift-R"

# Pressing this will reset the selected instance.
wall_reset = ""

# Pressing this will play the selected instance and reset all other instances.
wall_reset_others = "Ctrl-Shift"

# Pressing this will play the selected instance.
wall_play = "Shift"

# Pressing this will lock the selected instance.
wall_lock = "Ctrl"

[wall]
# Whether or not to press F1 when focusing instances. If you use this, turn on
# f1 in your standard settings file.
hide_gui = false

# Whether or not to stretch windows while on the wall for better visibility.
# Works with or without fullscreen.
stretch_windows = false

# The width to stretch windows to on the wall scene.
stretch_width = 1600

# The height to stretch windows to on the wall scene.
stretch_height = 300

# The width to unstretch windows to when being played.
unstretch_width = 1920

# The height to unstretch windows to when being played.
unstretch_height = 1080

# The X coordinate to move Minecraft windows to when resizing them. Only
# takes effect if stretch_windows is enabled.
resize_x = 0

# The Y coordinate to move Minecraft windows to when resizing them. Only
# takes effect if stretch_windows is enabled.
resize_y = 0

# Whether or not to enable mouse support on the wall. Enabling this will allow
# you to click on instances to perform various actions instead of having to use
# the number keys. Note that enabling this does not disable the number keys.
# NOTE: Mouse support currently doesn't work with moving wall. Please make sure to keep this as false while using moving wall.
use_mouse = false

# If enabled, resetting from within an instance will switch to the first locked
# instance (if any) instead of going back to the wall.
# NOTE: This feature doesn't work with moving wall at the moment. Please make sure to keep this as false while using moving wall.
goto_locked = false

# Whether or not to create the "sleepbg.lock" file when an instance is being
# played. Requires SleepBackground >=3.6 to have any effect. 
sleepbg_lock = true

# You can supply a custom path to "sleepbg.lock" here in case you set the
# Java USER.HOME property to somewhere else. Leave blank to use the default,
# which is your home directory.
sleepbg_lock_path = "/home/my_user"

# More advanced wall settings, mainly aimed towards increasing performance.
[advanced_wall]
# Whether or not to use advanced affinity. All other affinity settings below
# only take effect if this is enabled. All affinity settings must be equal to
# or less than the number of CPU threads you have.
#
# Instance types:
# - Idle:   Done generating, paused
# - Low:    On the preview, generated more than low_threshold
# - Mid:    A high priority instance in the background while another instance is being played
# - High:   On the dirt screen or below low_threshold
# - Active: The instance currently being played
affinity = false

# Splits the instances so that half one on run CCX and the other half run on
# the other CCX. If enabled, only half as many CPUs will be available for the
# below configuration options. Only use this if you have an AMD CPU with 2
# CCXs.
ccx_split = false

# Number of CPUs to run idle instances on.
affinity_idle = 1

# Number of CPUs to run low priority instances on.
affinity_low = 4

# Number of CPUs to run mid priority instances on.
affinity_mid = 8

# Number of CPUs to run high priority instances on.
affinity_high = 12

# Number of CPUs to run the actively played instance on.
affinity_active = 12

# The world generation percentage to reach before moving an instance
# from high priority to low priority.
low_threshold = 20

# Whether or not to freeze instances on the wall as they approach 100%
# world generation (to eliminate the rendering lag on world load.) Requires
# the Freeze Filter OBS plugin.
freeze_previews = false

# What percentage to freeze previews at.
freeze_threshold = 90

# Whether or not to hide instances from the wallwhile they are on the dirt
# screen.
hide_instances = false

# How to crop instances on the wall scene (left x right x top x bottom). Only
# useful for preview freezing to hide the chunkmap.
crop_instances = "0x0x0x0"
